### ISSUE TITLE
add metrics repository feature

### ISSUE THREAD

**Issue by liunan10** [margitaii/pydeequ#9]
Hello,

The metrics repository feature is very useful for deequ. I didn't see this function or feature implemented in pydeequ.

I have a few questions about that feature implementation
(1) why repository feature is not there in existing pydeequ
(2) is there any roadmap to add it ?
(3) whats involved in adding that feature ? Can you pls share your thoughts? Thanks a lot.

Best

**Comment by margitaii** [comment]
Hi @liunan10 ,

Thanks for your request. Well, at the first place I just wanted to implement the very basic features of Deequ so that data scientists can use it for prototyping an ETL pipeline. I fully agree, the metrics repository is very useful and most prob not just in production env but also during development.

Currently I do not have a roadmap but in the next days I'll recap again on this project because in the recent months I was not active. Implementing the metrics repo feature depends on the Scala classes used in Deequ and whether they can be easily wrapped with py4j or not. (Just an example is the #4  where I do not know how to wrap the Regex Scala class in python)
I need to have a look and will come back to you soon. If you have experience with these and have ideas please let me know as I am happy to welcome contributors to this project :)

**Comment by margitaii** [comment]
Hi @liunan10 , I implemented the basic (file system based) metrics repository feature (see src/pydeequ/metricsrepo.py module)
